# Generated by Django 4.2.7 on 2023-11-27 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('fathers_name', models.CharField(blank=True, help_text='Указывать не обязательно', max_length=64, verbose_name='Отчество')),
                ('email', models.CharField(max_length=64, verbose_name='email')),
            ],
            options={
                'verbose_name': 'посетитель',
                'verbose_name_plural': 'Посетители',
                'ordering': ('second_name', 'first_name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_publish', models.BooleanField(default=False, help_text='Поставьте галочку, чтобы опубликовать.', verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.visitors', verbose_name='Автор публикации')),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ('-created_at',),
            },
        ),
    ]
