# Generated by Django 4.2.7 on 2023-11-27 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_comment_email_alter_comment_author_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Feedback',
        ),
    ]
